import os
import pandas as pd
from typing import List, Optional, TypedDict, Union
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage
from langchain_groq import ChatGroq # Updated to ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import StateGraph, END
import io
import sys
import re
import matplotlib
matplotlib.use('Agg') # Use 'Agg' backend for non-interactive plotting
import matplotlib.pyplot as plt

# Load environment variables (assuming you have your .env file with GROQ_API_KEY)
from dotenv import load_dotenv
load_dotenv()

# --- 1. Define AgentState (Updated for Milestone 3) ---
class AgentState(TypedDict):
    df: Optional[pd.DataFrame]
    original_df: Optional[pd.DataFrame]
    file_name: Optional[str]
    messages: List[BaseMessage]
    generated_code: Optional[str]        # NEW: Stores the Python code generated by LLM
    execution_result: Optional[str]      # NEW: Stores the output/error from code execution
    plot_saved_path: Optional[str]       # For saving plot file paths
    csv_saved_paths: List[str]           # For saving processed CSV file paths
    final_response: Optional[str]

# --- 2. LLM and Prompt Template ---
# Initialize the LLM (ensure GROQ_API_KEY environment variable is set)
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    raise ValueError("GROQ_API_KEY not found in environment variables. Please set it in a .env file.")

# Updated to ChatGroq based on your setup
llm = ChatGroq(api_key=GROQ_API_KEY, model_name="llama-3.1-8b-instant", temperature=0.0)

# Define the prompt for the LLM
PROMPT = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """You are a helpful data analysis assistant.
            You are given a Pandas DataFrame named `df`.
            Your goal is to answer questions about the data, clean it, transform it, or visualize it.
            You can generate Python code to perform these tasks.
            The code should be executable in a Python environment.
            When you generate code, ensure:
            - You only output Python code, nothing else (no natural language explanations, no markdown fences).
            - You do NOT use `input()` or other interactive functions.
            - If you need to print output, use `print()`.
            - If you generate plots, save them to a file (e.g., `plt.savefig('plots/plot.png')`) and make sure the code prints the path to the saved plot. Use `matplotlib.pyplot as plt`. Always include `plt.show()` after `plt.savefig()` to ensure plot is rendered and buffer is cleared for proper saving.
            - If you save a CSV, use `df.to_csv('data/output.csv', index=False)` and print the file path.
            - All necessary imports are included (e.g., `import pandas as pd`, `import matplotlib.pyplot as plt`, `import seaborn as sns`, `import numpy as np`).

            Here is the current state of the DataFrame (first 5 rows and info summary for context, if available):
            {df_head}
            {df_info}

            Here is the result of the last code execution (if any):
            {execution_result}

            Based on the user's request and the current DataFrame state, generate the Python code.
            """
        ),
        ("human", "{user_request}"),
    ]
)

# --- Helper function (from your original code, will be used by a node) ---
def generate_plot_filename(user_prompt: str) -> str:
    sanitized_prompt = re.sub(r'[^\w\s]', '', user_prompt).strip().replace(' ', '_')
    plot_type_match = re.search(r'(histogram|boxplot|scatter|line|bar)', user_prompt, re.IGNORECASE)
    plot_type = plot_type_match.group(1).lower() if plot_type_match else "plot"
    column_match = re.search(r'(of|for)\s+([a-zA-Z0-9_,\s]+)', user_prompt, re.IGNORECASE)
    column_name = ""
    if column_match:
        cols = [c.strip() for c in column_match.group(2).split(',') if c.strip()]
        if cols:
            column_name = cols[0]
            column_name = re.sub(r'[^\w]', '', column_name)
            column_name = column_name.lower()

    if column_name and plot_type:
        filename = f"{column_name}_{plot_type}.png"
    elif plot_type:
        filename = f"{plot_type}.png"
    elif sanitized_prompt:
        filename = f"{sanitized_prompt[:50]}.png"
    else:
        filename = "unnamed_plot.png"

    timestamp = pd.Timestamp.now().strftime("%Y%m%d_%H%M%S")
    return os.path.join("plots", f"{os.path.splitext(filename)[0]}_{timestamp}.png") # Ensure plot is saved in 'plots' dir

# --- 3. Nodes of the Graph ---

# Node 1: Loads the data from a file path provided in a HumanMessage
def load_data_node(state: AgentState) -> AgentState:
    messages = state.get("messages", [])
    file_path = None # Ensures 'file_path' exists in scope with a default 'None' value.

    # 1. Check if a file path can be extracted from the last HumanMessage
    if messages and isinstance(messages[-1], HumanMessage):
        file_path = messages[-1].content
    else:
        # Error scenario 1: No HumanMessage found, or messages list is empty
        print("[❌] Error: No file path provided in the initial HumanMessage.")
        messages.append(AIMessage(content="Error: Please provide a file path to load."))
        return {"df": None, "original_df": None, "file_name": None, "messages": messages}

    # 2. Check if the extracted file path is empty
    if not file_path:
        print("[❌] Error: File path is empty.")
        messages.append(AIMessage(content="Error: File path cannot be empty."))
        return {"df": None, "file_name": None, "messages": messages}

    # 3. Attempt to read the CSV file
    try:
        df = pd.read_csv(file_path)
        print(f"[✅] Loaded dataset: {file_path} with shape {df.shape}")
        messages.append(AIMessage(content=f"Dataset '{file_path}' loaded successfully with shape {df.shape}."))
        # Store a copy of the original DataFrame to allow resetting later if needed
        return {"df": df.copy(), "original_df": df.copy(), "file_name": file_path, "messages": messages}
    except Exception as e:
        print(f"[❌] Failed to load dataset from '{file_path}': {e}")
        messages.append(AIMessage(content=f"Failed to load dataset from '{file_path}': {e}"))
        return {"df": None, "original_df": None, "file_name": None, "messages": messages}

# NEW NODE for Milestone 3
# Node 2: Generates Python code using the LLM
def generate_code_node(state: AgentState) -> AgentState:
    df_head = ""
    df_info = ""
    if state["df"] is not None:
        # Using to_markdown() for better LLM readability
        df_head = state["df"].head().to_markdown()
        # Capturing df.info() output (which goes to stderr by default)
        buf = io.StringIO()
        state["df"].info(buf=buf)
        df_info = buf.getvalue()

    # Get the latest human message for the user_request
    user_request = ""
    for msg in reversed(state["messages"]):
        if isinstance(msg, HumanMessage):
            user_request = msg.content
            break

    # Prepare the prompt
    prompt_messages = PROMPT.format_messages(
        df_head=df_head,
        df_info=df_info,
        execution_result=state.get("execution_result", "No previous execution result."),
        user_request=user_request
    )

    # Invoke the LLM to generate code
    print("[⚙️] Generating code...")
    ai_response = llm.invoke(prompt_messages)
    generated_code = ai_response.content.strip()

    # Append LLM's thought process (optional, but good for debugging)
    # messages.append(AIMessage(content=f"Generated code:\n```python\n{generated_code}\n```"))
    print(f"[✨] Code generated:\n```python\n{generated_code}\n```")

    return {"generated_code": generated_code, "messages": state["messages"] + [AIMessage(content="Generating code for your request.")]}

# NEW NODE for Milestone 3
# Node 3: Executes the generated Python code
def execute_code_node(state: AgentState) -> AgentState:
    generated_code = state.get("generated_code")
    messages = state.get("messages", [])
    df = state.get("df")
    original_df = state.get("original_df")
    file_name = state.get("file_name")
    plot_saved_path = state.get("plot_saved_path")
    csv_saved_paths = state.get("csv_saved_paths", [])

    if not generated_code:
        print("[❌] Error: No code to execute.")
        messages.append(AIMessage(content="Error: No code was generated to execute."))
        return {"execution_result": "No code to execute.", "messages": messages}

    # Prepare a dictionary for local variables that the executed code can access
    # This makes 'df', 'original_df', 'file_name' available inside the exec() context
    # Also, make matplotlib.pyplot available as 'plt' for saving plots
    # And pandas as 'pd', numpy as 'np', seaborn as 'sns'
    exec_globals = {
        'df': df,
        'original_df': original_df,
        'file_name': file_name,
        'plt': plt,
        'pd': pd,
        'np': __import__('numpy'), # Import numpy on the fly
        'sns': __import__('seaborn'), # Import seaborn on the fly
        'io': io, # For potential string buffer operations within the generated code
        'sys': sys # For redirecting stdout/stderr
    }
    # Ensure any new dfs created by the agent are captured
    exec_locals = {} # Use exec_locals to capture variables modified/created by exec()

    # Capture stdout and stderr
    old_stdout = sys.stdout
    old_stderr = sys.stderr
    redirected_output = io.StringIO()
    redirected_error = io.StringIO()
    sys.stdout = redirected_output
    sys.stderr = redirected_error

    execution_result = ""
    try:
        # Execute the generated code
        exec(generated_code, exec_globals, exec_locals)

        # Get captured output
        stdout_output = redirected_output.getvalue()
        stderr_output = redirected_error.getvalue()

        if stdout_output:
            execution_result += f"Output:\n{stdout_output}\n"
        if stderr_output:
            execution_result += f"Error Output:\n{stderr_output}\n"

        # Update df and other relevant states if they were modified/created in exec_locals
        # This is CRUCIAL to persist changes made by the generated code
        if 'df' in exec_locals and isinstance(exec_locals['df'], pd.DataFrame):
            df = exec_locals['df']
            print(f"[📊] DataFrame updated by code. New shape: {df.shape}")
        # Else, if df was not explicitly modified/created in exec_locals, it remains the df from state (exec_globals['df'])
        # No need for an else here, as df already holds the initial state's df

        # Check for saved plots or CSVs (basic regex parsing, can be more robust)
        # This part assumes the LLM prints messages about saving
        plot_matches = re.findall(r"Plot saved to (.*\.png|.*\.jpg|.*\.jpeg)", execution_result)
        if plot_matches:
            plot_saved_path = plot_matches[-1] # Take the last one if multiple are saved
            print(f"[🖼️] Detected saved plot: {plot_saved_path}")

        csv_matches = re.findall(r"CSV saved to (.*\.csv)", execution_result)
        if csv_matches:
            # Append new CSV paths, avoid duplicates
            for csv_path in csv_matches:
                if csv_path not in csv_saved_paths:
                    csv_saved_paths.append(csv_path)
            print(f"[📁] Detected saved CSVs: {csv_saved_paths}")


    except Exception as e:
        execution_result = f"Execution failed: {e}\n"
        # If there's any stderr output, add it too
        stderr_output = redirected_error.getvalue()
        if stderr_output:
             execution_result += f"Error Output:\n{stderr_output}\n"
        print(f"[❌] Code execution failed: {e}")

    finally:
        # Restore stdout and stderr regardless of success or failure
        sys.stdout = old_stdout
        sys.stderr = old_stderr

    messages.append(AIMessage(content=f"Code execution result:\n```\n{execution_result}\n```"))

    return {
        "df": df, # Return the potentially updated df
        "execution_result": execution_result,
        "messages": messages,
        "plot_saved_path": plot_saved_path,
        "csv_saved_paths": csv_saved_paths
    }


# --- 4. Conditional Edge Logic ---
# NEW FUNCTION for Milestone 3
def should_continue(state: AgentState) -> str:
    messages = state["messages"]
    last_message = messages[-1]

    # Check if the last message is an AI message indicating code execution results
    if isinstance(last_message, AIMessage) and "Code execution result:" in last_message.content:
        # Based on the execution result, decide whether to continue generating code
        # or conclude the interaction.

        execution_result_content = state.get("execution_result", "")

        if "Execution failed" in execution_result_content:
            print("[🔄] Execution failed. Looping back to generate more code...")
            messages.append(AIMessage(content="Previous code execution failed. Let's try to fix it. Please refine your request or suggest an alternative."))
            return "generate_code" # Go back to generate more code if execution failed
        elif state.get("plot_saved_path") or state.get("csv_saved_paths"):
            # If a plot or CSV was saved, it's a good time to potentially end or ask for next steps
            print("[✅] Plot/CSV saved. Considering ending or asking for next steps.")
            messages.append(AIMessage(content="Plot or CSV file was successfully saved. What would you like to do next?"))
            # For this milestone, let's allow it to potentially end after a save action.
            # In a real agent, you might want another node to summarize or ask.
            return END
        elif "No code to execute." in execution_result_content:
             # This means generate_code_node likely failed to produce code
             print("[⚠️] No code was generated for execution. Regenerating.")
             messages.append(AIMessage(content="The LLM did not generate code. Please refine your request or provide more context."))
             return "generate_code"
        else:
            # If code ran successfully and no specific save action was detected,
            # we can decide based on common outputs.
            # If the LLM produces descriptive output, it might be done.
            # Otherwise, it might need to generate more code.
            # For now, let's assume if it executed without explicit failure, it might be trying to present info.
            print("[🤔] Code executed successfully. Deciding next step...")
            # For Milestone 3, let's assume successful execution leads to ending for now,
            # or you can loop to generate_code if you expect more interaction.
            # A more advanced agent would ask for next steps or interpret if a "final answer" was given.
            messages.append(AIMessage(content="Code executed successfully. What's next? (Type 'exit' to end)"))
            return END # For now, assume successful execution leads to end.

    # If the last message is from the user, or if we just loaded data, generate code.
    # This acts as the default routing if none of the specific conditions above match.
    print("[➡️] User message or data loaded. Proceeding to generate code.")
    return "generate_code" # Default path after data load or if a new user request comes in

# --- 5. Build the Graph ---
workflow = StateGraph(AgentState)

# Add nodes
workflow.add_node("load_data", load_data_node)
workflow.add_node("generate_code", generate_code_node)       # NEW NODE for M3
workflow.add_node("execute_code", execute_code_node)         # NEW NODE for M3

# Set entry point
workflow.set_entry_point("load_data")

# Add edges
# After loading data, always generate code
workflow.add_edge("load_data", "generate_code")

# After generating code, always execute it
workflow.add_edge("generate_code", "execute_code")

# After executing code, use a conditional edge
# The 'should_continue' function decides the next state
workflow.add_conditional_edges(
    "execute_code", # From this node
    should_continue, # Use this function to decide
    {
        "generate_code": "generate_code", # If should_continue returns "generate_code", go to generate_code node
        END: END                          # If should_continue returns END, terminate the graph
    }
)

# Compile the graph
app = workflow.compile()

# --- 6. Main Execution Loop ---
if __name__ == "__main__":
    # Ensure the 'data' and 'plots' directories exist for saving files
    os.makedirs("data", exist_ok=True)
    os.makedirs("plots", exist_ok=True)

    print("Welcome to the Data Analysis Agent (Milestone 3)!")
    print("Please provide the path to a CSV file to begin (e.g., data/titanic.csv).")
    print("Then, you can ask questions or request actions (e.g., 'show head', 'describe data', 'plot age distribution').")
    print("Type 'exit' to quit.")

    # Loop for continuous interaction
    while True:
        user_input = input("\nYou: ").strip()
        if user_input.lower() == 'exit':
            print("Exiting agent. Goodbye!")
            break

        # Get current state from the app if it's already running
        # This handles subsequent turns by fetching the current state of the graph
        # before invoking it again.
        current_state_values = app.get_state().values if app.get_state() else None
        current_df_loaded = current_state_values.get("df") is not None if current_state_values else False

        initial_messages = []
        if not current_df_loaded:
            # First input is always the file path
            initial_messages.append(HumanMessage(content=user_input))
            print("[🤖] Initializing agent with file path...")
            # Set initial state for the *first* invocation
            initial_graph_state = {
                "messages": initial_messages,
                "csv_saved_paths": [],
                "plot_saved_path": None,
                "generated_code": None,
                "execution_result": None,
                "final_response": None,
                "df": None,
                "original_df": None,
                "file_name": None
            }
            final_state = app.invoke(initial_graph_state)
        else:
            # Subsequent inputs are user requests for analysis
            print("[🤖] Processing your request...")
            # For subsequent invocations, we need to preserve the df and other existing state.
            # LangGraph's app.invoke() will merge the initial_state with the current_state,
            # but for clarity, we explicitly update messages here.
            # The current_state_values obtained via app.get_state().values already has the current df.
            # We just need to add the new HumanMessage to the existing messages list.
            full_current_messages = current_state_values.get('messages', []) + [HumanMessage(content=user_input)]
            # Construct the state to pass, primarily updating messages
            state_for_invoke = {
                **current_state_values, # Start with all current state values
                "messages": full_current_messages # Add the new human message
            }
            # Remove keys that are meant to be generated or cleared on new turn
            state_for_invoke["generated_code"] = None
            state_for_invoke["execution_result"] = None
            state_for_invoke["final_response"] = None
            state_for_invoke["plot_saved_path"] = None # Clear plot path for new turn's potential plot


            # Invoke the graph with the updated state
            final_state = app.invoke(state_for_invoke)


        # --- Display Final State (for debugging/demonstration) ---
        print("\n--- Current Agent State Summary ---")
        if final_state and final_state.get("df") is not None:
            print(f"DataFrame present. Shape: {final_state['df'].shape}")
            # print("DataFrame Head:\n", final_state['df'].head().to_markdown()) # Can be too verbose
        else:
            print("No DataFrame loaded or an error occurred.")

        # Print the latest AI message
        if final_state and final_state.get("messages"):
            latest_ai_message = None
            # Iterate backwards to find the last AIMessage generated by a node
            for msg in reversed(final_state["messages"]):
                if isinstance(msg, AIMessage):
                    latest_ai_message = msg
                    break
            if latest_ai_message:
                print(f"\nAI: {latest_ai_message.content}")
            else:
                print("\nAI: (No direct AI response for the last turn, check logs for progress)")


        # --- Detailed Debugging Output (optional, for development) ---
        # print("\n--- Full Agent State ---")
        # from pprint import pprint
        # pprint(final_state)

        # Print code and execution result for this turn
        if final_state and final_state.get("generated_code"):
            print(f"\nLast Generated Code:\n```python\n{final_state['generated_code']}\n```")
        if final_state and final_state.get("execution_result"):
            print(f"\nLast Execution Result:\n```\n{final_state['execution_result']}\n```")

        # If a plot or CSV was saved, inform the user
        if final_state and final_state.get("plot_saved_path"):
            print(f"\nPlot saved to: {final_state['plot_saved_path']}")
        if final_state and final_state.get("csv_saved_paths"):
            print(f"\nCSVs saved to: {final_state['csv_saved_paths']}")